RENAME TABLE alwi.house_upload to alwi.order_list;
SELECT * FROM alwi.order_list;

-- Sales, Subscription & Customer Behavior Analysis

-- 1. What is the total revenue generated by male vs. female customers?
SELECT Gender, SUM(purchase_amount) AS Revenue_generated 
FROM alwi.order_list
GROUP BY Gender;


-- 2. Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, discount_applied, purchase_amount
FROM alwi.order_list
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM alwi.order_list);


-- 2a How many members spent more than the average purchase amount?
SELECT COUNT(DISTINCT customer_id) AS members_above_average, gender
FROM alwi.order_list
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM alwi.order_list)
GROUP BY gender;


-- 3. Which are the top 10 products with the highest average review rating?
SELECT item_purchased,
ROUND(AVG(CAST(review_rating AS DECIMAL(3,2))), 2) AS "Average product rating"
FROM alwi.order_list
GROUP BY item_purchased 
ORDER BY "Average product rating" DESC
LIMIT 10;


-- 4. Compare the average Purchase amounts between standard and express shipping?
SELECT shipping_type,
ROUND(AVG(purchase_amount),2) AS "Average Purchase Amounts"
FROM alwi.order_list
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;


-- 5. Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS Average_Spend,
ROUND(SUM(purchase_amount),2) AS Total_revenue
FROM alwi.order_list
GROUP BY subscription_status
ORDER BY Average_Spend, Total_revenue;


-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(
  100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
  2
) AS discount_rate
FROM alwi.order_list
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- 7. Segment customers into new, returning and loyal based on previous purchases
USE alwi;

WITH customer_type AS (
  SELECT customer_id, previous_purchases,
  CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
  END AS customer_segment
  FROM alwi.order_list
)
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


-- 8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
  SELECT 
    category, 
    item_purchased, 
    COUNT(customer_id) AS total_orders,
    ROW_NUMBER() OVER (
      PARTITION BY category 
      ORDER BY COUNT(customer_id) DESC
    ) AS item_rank
  FROM alwi.order_list
  GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- 9. Are customers who are repeat buyers (>5 previous purchases) also likely to subscribe?
SELECT COUNT(customer_id) AS repeat_buyers, subscription_status
FROM alwi.order_list
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- 10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS revenue_contribution
FROM alwi.order_list
GROUP BY age_group
ORDER BY revenue_contribution DESC;
